server:
  port: 3344
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ruanun/springcloud-config
      #          username:
      #          password:
      label: master  #读取的分支
  rabbitmq:
    host: 192.168.18.139
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    service-url:
      # 集群版
      #      defaultZone: http://eureka16001.com:16001/eureka,http://eureka16000.com:16000/eureka
      #单机版
      defaultZone: http://localhost:16000/eureka
      #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetch-registry: true
