server:
  port: 17001

spring:
  application:
    name: cloud-order-service


eureka:
  client:
    service-url:
      # 集群版
      defaultZone: http://eureka16001.com:16001/eureka,http://eureka16000.com:16000/eureka
      #单机版
#      defaultZone: http://localhost:16000/eureka
      #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
#    fetch-registry: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 1000
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 50000
logging:
  level:
    com.ruanun.springcloud.service: debug