server:
  port: 18004
spring:
  application:
    name: cloud-providerconsul-payment
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}