server:
  port: 20002
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务的地址
management:
  endpoints:
    web:
      exposure:
        include: '*'